### ISSUE TITLE
Which text encoder ?

### ISSUE THREAD

**Issue by ghost** [sidward14/Style-AttnGAN#14]
Did you use GPT-2 or biLSTM for the text encoder to get the [results shown in the table in the README.md file](https://github.com/sidward14/Style-AttnGAN/blob/master/README.md#quantitative-performance-comparisons-on-birds-dataset-cub-200-2011)? Thanks

**Comment by sidward14** [comment]
Hello! I used biLSTM. I tested both and biLSTM was better.

**Comment by ghost** [comment]
Thanks for your reply. I have another question.

Do you know why biLSTM performed better in this case? Generally, the Transformers architecture is considered better than RNNs or biLSTMs for text-related tasks. Thanks.

**Comment by sidward14** [comment]
Yes transformer is usually better. This may be a caveat: it is using word embeddings for attention with spatial features. It may not be superior in this special case.

Another reason may be that my method for capturing the sentence embedding isn't optimal. See here:
https://github.com/sidward14/Style-AttnGAN/issues/16
