### ISSUE TITLE
Word features and sentence feature

### ISSUE THREAD

**Issue by ghost** [sidward14/Style-AttnGAN#16]
![picture](https://github.com/sidward14/Style-AttnGAN/assets/138822194/738666de-0642-4f47-8d61-16193d6bcde0)

My question is that if you use GPT-2 instead of LSTM for the text encoder, how did you calculate the word features and sentence feature? Can you explain more details?

**Comment by sidward14** [comment]
Good question! I use the last dimension of the words feature vector for the global sentence feature vector since it best contains context for all the words in the sentence.

If you have a better idea, I would love to collaborate!

**Comment by sidward14** [comment]
Here is where I do it for evaluation in the code:
https://github.com/sidward14/Style-AttnGAN/blob/8aa8da6601725c425e272f0bededa32033a38d84/code/eval.py#L123

**Comment by ghost** [comment]
Ok, I was scrolling the `pretrain_DAMSM.py` file, and I saw these 2 lines:

https://github.com/sidward14/Style-AttnGAN/blob/8aa8da6601725c425e272f0bededa32033a38d84/code/pretrain_DAMSM.py#L93-L94

What does these 2 lines do ? Are these for calculating the word features and sentence feature for GPT-2 text encoder ? Can someone explain, thanks.

**Comment by sidward14** [comment]
Yes, that's exactly what it is. It's applying the same concept for using the last dimension of the words features to get the sentence feature vector. These are then used for deep attentional multimodal similarity.

**Comment by ghost** [comment]
Okay, I understand how you calculated the sentence feature. For the word features, did you use this line to calculate them?

https://github.com/sidward14/Style-AttnGAN/blob/8aa8da6601725c425e272f0bededa32033a38d84/code/pretrain_DAMSM.py#L93

Can you explain how you calculated the word features? Thanks.

**Comment by sidward14** [comment]
Yes, that is the line to calculate the word features.

When `text_encoder_type == 'transformer'`, I use the `GPT2Model` from huggingface's transformers package as `nlp_model`. You can reference this `GPT2Model` to learn more of what's going on under the hood.

https://github.com/sidward14/Style-AttnGAN/blob/8aa8da6601725c425e272f0bededa32033a38d84/code/pretrain_DAMSM.py#L32
