### ISSUE TITLE
The pretrained DAMSM + GPT-2 model

### ISSUE THREAD

**Issue by ghost** [sidward14/Style-AttnGAN#26]
Do you have pre-trained DAMSM model that uses GPT-2 for the text encoder? Thanks

**Comment by sidward14** [comment]
Sorry was out of town!

I didn't pretrain a DAMSM with GPT-2. You'll have to train one yourself using the instructions in the readme. Sorry!

**Comment by ghost** [comment]
Thanks for your help.
