### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by EricYu97** [sidward14/Style-AttnGAN#4]
Hi, I have seen your instructions for using a custom dataset. However, when I was trying to execute the pretrain_DAMSM.py, the program required captions.pickle file in the dataset path. It seems like I should do some data preprocessing work before the training. Do you have any ideas? Thanks!

**Comment by EricYu97** [comment]
Solved. The train.txt and test.txt should be properly edited and the captions.pickle can be generated from these files.

**Comment by sidward14** [comment]
Great! I will investigate further to make sure sometime this week. Sorry, very busy this week
