### ISSUE TITLE
About dimension problem when training GAN

### ISSUE THREAD

**Issue by Blackboard-s** [sidward14/Style-AttnGAN#5]
In “D_GET_LOGITS” - “forward”  
         h_c_code = torch.cat((h_code, c_code), 1)
there is an error:

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 8 but got size 4 for tensor number 1 in the list.

I dont know the reason

**Comment by sidward14** [comment]
Sorry for late reply, very busy this week. I will address this sometime this week!

**Comment by sidward14** [comment]
Is this with your own custom dataset? That's very strange. Might be a problem with your batch size, tell me the shape of h_code and c_code right before it goes into h_c_code = torch.cat((h_code, c_code), 1).

**Comment by sidward14** [comment]
I'm going to go ahead and close this, seems like it's working for others. But feel free to reach out if you continue to have problems!
