### ISSUE TITLE
load model 

### ISSUE THREAD

**Issue by mehrshadmmt** [sidward14/Style-AttnGAN#8]
Hello, how can I use the saved model from output/model/ 
I'm running code on google colab and I must to save model after some epochs.
Please guide me do this.

**Comment by mehrshadmmt** [comment]
I have another question how can i give my sentences to genersted model to genrate  some words??,,,

**Comment by sidward14** [comment]
Hello, sorry for the long wait. Very busy at work.

You specify the path to the saved model in the NET_G key in the yaml file you're using. NET_E should be the same for both training and inference yaml files. 

Does that answer your question?

**Comment by mehrshadmmt** [comment]
Hello, thanks for your reply,
I have been solved this issue, but I have another question. 
How can I use **Oxford-102** flower dataset in this code?

**Comment by sidward14** [comment]
No problem

I have a section on using your own dataset: https://github.com/sidward14/Style-AttnGAN#custom-dataset
