### ISSUE TITLE
flowers dataset

### ISSUE THREAD

**Issue by mehrshadmmt** [sidward14/Style-AttnGAN#9]
Can I use oxford 102 flower dataset instead of birds dataset in this code?
If yes can you help me how to do this?

**Comment by sidward14** [comment]
Yes you can! Please see here:
https://github.com/sidward14/Style-AttnGAN#custom-dataset 

Let me know if you have any further questions.

**Comment by mehrshadmmt** [comment]
I followed the steps that you mentioned, but unfortunately I have problem with caption.pickle file. In the caption files of this dataset, there is no .pickle file. Also, the code need it for training and I don't know how to find this file.
please help me to solve it.

**Comment by sidward14** [comment]
The captions.pickle file is just for train / test split. Another way of doing train / test split is by having a train.txt and text.txt file. That's how I do it in the barebones birds example. Each line in train.txt and text.txt refers to an image in the images dir and it's corresponding captions in the text dir.

So for your flowers dataset, I recommend setting it up like that: a train.txt for your training dataset and a test.txt for your test dataset. This way, you don't need a captions.pickle file.

Does that make sense?
